[package]
authors = ["Sebastian Wicki <gandro@gmx.net>"]
name = "grpcdump"
version = "0.1.0"

[dependencies]
clap = "2.30.0"
failure = "0.1.1"
h2 = "0.1.0"
pcap = "0.7.0"
smoltcp = { version = "0.4", default-features = false }
